### ISSUE TITLE
Markdown code block(s) not wrapping

### ISSUE THREAD

**Issue by ThomasParmentier** [HoGentTIN/linux-training-hogent#8]
![image](https://github.com/user-attachments/assets/51e7cc91-bd71-40d6-b453-a2811b1d7284)

Markdown code blocks don't seem to wrap correctly. This one is #[in section 2.4 ](https://github.com/HoGentTIN/linux-training-hogent/blob/main/modules/package_management/033_packages_other_theory.md#pip-the-python-package-manager).

Writing it down now, I'll have a look at the build config options later.

**Comment by bertvv** [comment]
[This line](https://github.com/HoGentTIN/linux-training-hogent/blob/382c1be26068696bae6b8e35807636aec137b759/templates/book/metadata-block.yml.j2#L14) is supposed to guarantee that lines are split. See also:

- <https://github.com/jgm/pandoc/issues/4302>
- <https://stackoverflow.com/questions/20788464/pandoc-doesnt-text-wrap-code-blocks-when-converting-to-pdf>
- <https://tex.stackexchange.com/questions/323329/pandoc-code-blocks-in-markdown-with-very-long-lines-get-cut-off-when-outputting>
